#!/usr/bin/env python3
"""Mark every file blocked on the Structurize port and list it for exclusion.

Structurize has no 26.2 build yet. The 147 files that import it cannot be ported
against an API nobody has seen, so they are marked in place and kept out of
compilation until the library lands -- rather than being half-ported on guesses.

Writes 26.2/structurize-blocked.txt, which build.gradle feeds to sourceSets as
exclude patterns. Re-run after the library arrives to see the list shrink to zero.

Usage: mark-structurize.py <source-root> <list-output>
"""
import os
import re
import sys

ROOT = sys.argv[1] if len(sys.argv) > 1 else "26.2/src/main/java"
OUT = sys.argv[2] if len(sys.argv) > 2 else "26.2/structurize-blocked.txt"

MARKER = (
    "// PORT-TODO(structurize): waiting on the 26.2 port of com.ldtteam.structurize.\n"
    "// This file is excluded from compilation via 26.2/structurize-blocked.txt and has\n"
    "// NOT been ported to 26.2 -- everything in it is still 1.21.1 NeoForge code.\n"
)
PACKAGE = re.compile(r"^package\s+[\w.]+;\s*$", re.M)
USES_STRUCTURIZE = re.compile(r"\bcom\.ldtteam\.structurize\b")

blocked = []
marked = 0
for dirpath, _, files in os.walk(ROOT):
    for f in sorted(files):
        if not f.endswith(".java"):
            continue
        path = os.path.join(dirpath, f)
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        if not USES_STRUCTURIZE.search(text):
            continue
        blocked.append(os.path.relpath(path, ROOT))
        if "PORT-TODO(structurize)" in text:
            continue
        m = PACKAGE.search(text)
        if not m:
            print(f"no package statement, marker not inserted: {path}")
            continue
        text = text[:m.end()] + "\n\n" + MARKER + text[m.end():]
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        marked += 1

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("# Files blocked on the Structurize 26.2 port — excluded from compilation.\n")
    fh.write("# Generated by porting-26.2/mark-structurize.py. Do not hand-edit.\n")
    for p in sorted(blocked):
        fh.write(p + "\n")

print(f"blocked files: {len(blocked)}")
print(f"markers inserted: {marked}")
print(f"list written to: {OUT}")
